services:
  # Backend Service (Node.js)
  - type: web
    name: treatsby-backend
    runtime: node
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  # Frontend Service (React)
  - type: web
    name: treatsby-frontend
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    startCommand: "" # This is the critical change to prevent npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://treatsbyshawty-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
