services:
  # Backend Service (Node.js)
  - type: web
    name: treatsby-backend
    runtime: node
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  # Frontend Service (React Static Site)
  - type: static
    name: treatsby-frontend
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    publishDir: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: treatsby-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
